project:
  type: book
  output-dir: docs

book:
  title: "R for Data Science Exercises"
  author: "Pete Lawson"
  chapters:
    - index.qmd
    - introduction.qmd
    - part: "Explore"
      chapters:
        - explore-introduction.qmd
        - data-visualization.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: custom.css
  pdf:
    documentclass: scrreprt



